### ISSUE TITLE
problem making dependencies

### ISSUE THREAD

**Issue by BELKHIR** [thackl/cross-species-scaffolding#5]
Dear all,

Just to report 2 problems 
* In the make dependencies util/samtools depends on htslib which is installed in util/bcftools, so one must install bcftools before samtools.
* in cross-mates the "Possible SOAP-denovo config for libraries:" is not valide because the R2 is the same as the R1 reads name !

Regards

**Comment by thackl** [comment]
Thanks for reporting. Should be fixed!
