### ISSUE TITLE
Can't locate Fasta/Parser.pm

### ISSUE THREAD

**Issue by AMMMachado** [thackl/cross-species-scaffolding#7]
Dear  thackl ,
First of all thank you for the program. 
It is a very useful program to build genomes with few resources available. 
Im working on cluster, centos 7, 512Gb ram and 32 cpus. 

I tried to run the "make sample-yeast" to test the installation of the program, without success.

Seems to have all programs in the bashrc, but give me always the error below, and the mp files are empty.

#5 Log.file
make sample-yeast
hash bwa || { echo "bwa required in PATH" 1>&2 && exit 1; }
hash curl || { echo "curl required in PATH" 1>&2 && exit 1; }
hash fastq-dump || { echo "fastq-dump required in PATH" && exit 1; }
cd samples/yeast && ../../bin/cross-mates -s -t 4 -i 500,2000,5000,10000 S228c.fa CLIB324.fq
[18:30:39] bwa .. ok
[18:30:39] samtools .. ok
[18:30:39] bcftools .. ok
[18:30:39] vcfutils.pl .. ok
[18:30:39] seq-frag .. ok
[18:30:39] interleaved-split .. ok
[bwa_index] Pack FASTA... 0.14 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 7.06 seconds elapse.
[bwa_index] Update BWT... 0.09 sec
[bwa_index] Pack forward-only FASTA... 0.07 sec
[bwa_index] Construct SA from BWT and Occ... 2.26 sec
[main] Version: 0.7.17-r1198-dirty
[main] CMD: bwa index S228c.fa
[main] Real time: 12.414 sec; CPU: 9.628 sec
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 396040 sequences (40000040 bp)...
[M::process] read 396040 sequences (40000040 bp)...
[M::mem_process_seqs] Processed 396040 reads in 36.060 CPU sec, 8.922 real sec
[M::mem_process_seqs] Processed 396040 reads in 36.115 CPU sec, 8.918 real sec
[M::process] read 396040 sequences (40000040 bp)...
[M::process] read 396040 sequences (40000040 bp)...
[M::mem_process_seqs] Processed 396040 reads in 36.844 CPU sec, 9.019 real sec
[M::mem_process_seqs] Processed 396040 reads in 37.512 CPU sec, 9.280 real sec
[M::process] read 396040 sequences (40000040 bp)...
[M::process] read 396040 sequences (40000040 bp)...
[M::mem_process_seqs] Processed 396040 reads in 38.666 CPU sec, 9.490 real sec
[M::mem_process_seqs] Processed 396040 reads in 36.277 CPU sec, 8.954 real sec
[M::process] read 396040 sequences (40000040 bp)...
[M::process] read 396040 sequences (40000040 bp)...
[M::mem_process_seqs] Processed 396040 reads in 36.093 CPU sec, 8.841 real sec
[M::process] read 396040 sequences (40000040 bp)...
[M::mem_process_seqs] Processed 396040 reads in 36.962 CPU sec, 9.055 real sec
[M::process] read 126279 sequences (12754179 bp)...
[M::mem_process_seqs] Processed 396040 reads in 36.274 CPU sec, 8.939 real sec
[M::mem_process_seqs] Processed 126279 reads in 11.582 CPU sec, 2.864 real sec
[main] Version: 0.7.17-r1198-dirty
[main] CMD: bwa mem -t 4 S228c.fa /dev/fd/63
[main] Real time: 100.592 sec; CPU: 344.304 sec
[bam_sort_core] merging from 0 files and 4 in-memory blocks...
[warning] samtools mpileup option `u` is functional, but deprecated. Please switch to using bcftools mpileup in future.
[mpileup] 1 samples in 1 input files
Note: none of --samples-file, --ploidy or --ploidy-file given, assuming all sites are diploid
bash -c seq-frag pe -p -s -i 500 -l 100 -c 10 <cross-mates-2019-05-03/target-cns.fq | interleaved-split 1>cross-mates-2019-05-03/CLIB324-pe-500_1.fq 2>cross-mates-2019-05-03/CLIB324-pe-500_2.fq 
bash -c seq-frag mp -p -s -i 2000 -l 100 -c 10 <cross-mates-2019-05-03/target-cns.fq | interleaved-split 1>cross-mates-2019-05-03/CLIB324-mp-2000_1.fq 2>cross-mates-2019-05-03/CLIB324-mp-2000_2.fq 
bash -c seq-frag mp -p -s -i 5000 -l 100 -c 10 <cross-mates-2019-05-03/target-cns.fq | interleaved-split 1>cross-mates-2019-05-03/CLIB324-mp-5000_1.fq 2>cross-mates-2019-05-03/CLIB324-mp-5000_2.fq 
bash -c seq-frag mp -p -s -i 10000 -l 100 -c 10 <cross-mates-2019-05-03/target-cns.fq | interleaved-split 1>cross-mates-2019-05-03/CLIB324-mp-10000_1.fq 2>cross-mates-2019-05-03/CLIB324-mp-10000_2.fq 
Can't locate Fasta/Parser.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/amachado/SW/cs-scaffolding/bin//../util//seq-scripts/bin/seq-frag line 8.
BEGIN failed--compilation aborted at /home/amachado/SW/cs-scaffolding/bin//../util//seq-scripts/bin/seq-frag line 8.
Can't locate Fasta/Parser.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/amachado/SW/cs-scaffolding/bin//../util//seq-scripts/bin/seq-frag line 8.
BEGIN failed--compilation aborted at /home/amachado/SW/cs-scaffolding/bin//../util//seq-scripts/bin/seq-frag line 8.
Can't locate Fasta/Parser.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/amachado/SW/cs-scaffolding/bin//../util//seq-scripts/bin/seq-frag line 8.
BEGIN failed--compilation aborted at /home/amachado/SW/cs-scaffolding/bin//../util//seq-scripts/bin/seq-frag line 8.
Can't locate Fasta/Parser.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/amachado/SW/cs-scaffolding/bin//../util//seq-scripts/bin/seq-frag line 8.
BEGIN failed--compilation aborted at /home/amachado/SW/cs-scaffolding/bin//../util//seq-scripts/bin/seq-frag line 8.
[18:40:59] Generated the following libraries:
/home/amachado/SW/cs-scaffolding/samples/yeast/cross-mates-2019-05-03/CLIB324-mp-2000_1.fq
/home/amachado/SW/cs-scaffolding/samples/yeast/cross-mates-2019-05-03/CLIB324-mp-2000_2.fq
/home/amachado/SW/cs-scaffolding/samples/yeast/cross-mates-2019-05-03/CLIB324-mp-5000_1.fq
/home/amachado/SW/cs-scaffolding/samples/yeast/cross-mates-2019-05-03/CLIB324-mp-5000_2.fq
/home/amachado/SW/cs-scaffolding/samples/yeast/cross-mates-2019-05-03/CLIB324-mp-10000_1.fq
/home/amachado/SW/cs-scaffolding/samples/yeast/cross-mates-2019-05-03/CLIB324-mp-10000_2.fq
/home/amachado/SW/cs-scaffolding/samples/yeast/cross-mates-2019-05-03/CLIB324-pe-500_1.fq
/home/amachado/SW/cs-scaffolding/samples/yeast/cross-mates-2019-05-03/CLIB324-pe-500_2.fq
[18:40:59] Possible SOAP-denovo config for libraries:
[LIB]
avg_ins=500
reverse_seq=0
asm_flags=2
rank=4
q1=cross-mates-2019-05-03/CLIB324-pe-500_1.fq
q2=cross-mates-2019-05-03/CLIB324-pe-500_2.fq
[LIB]
avg_ins=2000
reverse_seq=1
asm_flags=2
rank=5
q1=cross-mates-2019-05-03/CLIB324-mp-2000_1.fq
q2=cross-mates-2019-05-03/CLIB324-mp-2000_2.fq
[LIB]
avg_ins=5000
reverse_seq=1
asm_flags=2
rank=6
q1=cross-mates-2019-05-03/CLIB324-mp-5000_1.fq
q2=cross-mates-2019-05-03/CLIB324-mp-5000_2.fq
[LIB]
avg_ins=10000
reverse_seq=1
asm_flags=2
rank=7
q1=cross-mates-2019-05-03/CLIB324-mp-10000_1.fq
q2=cross-mates-2019-05-03/CLIB324-mp-10000_2.fq

Thank you in advance for all help.
André

**Comment by thackl** [comment]
I'm assuming you did not use `make dependencies` to install the external programs. That would have also downloaded the perl libraries you are missing. The easiest fix should be to go into you cross-species-scaffolding install directory and run the following lines
```
mkdir -p lib
cd lib
git clone https://github.com/BioInf-Wuerzburg/perl5lib-Fastq.git Fastq
git clone https://github.com/BioInf-Wuerzburg/perl5lib-Fasta.git Fasta
```

Let me know if that doesn't work

**Comment by AMMMachado** [comment]
Hi thackl,
During the instalation of software i used the make dependencies instruction. 

Now i deleted the folder and applied again the commands that you recommended.
 
" mkdir -p lib
cd lib
git clone https://github.com/BioInf-Wuerzburg/perl5lib-Fastq.git Fastq
git clone https://github.com/BioInf-Wuerzburg/perl5lib-Fasta.git Fasta
"
but the error continues to happen.

"Can't locate Fasta/Parser.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/amachado/SW/cs-scaffolding/bin//../util//seq-scripts/bin/seq-frag line 8.
BEGIN failed--compilation aborted at /home/amachado/SW/cs-scaffolding/bin//../util//seq-scripts/bin/seq-frag line 8.
Can't locate Fasta/Parser.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/amachado/SW/cs-scaffolding/bin//../util//seq-scripts/bin/seq-frag line 8.
BEGIN failed--compilation aborted at /home/amachado/SW/cs-scaffolding/bin//../util//seq-scripts/bin/seq-frag line 8.
Can't locate Fasta/Parser.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/amachado/SW/cs-scaffolding/bin//../util//seq-scripts/bin/seq-frag line 8.
BEGIN failed--compilation aborted at /home/amachado/SW/cs-scaffolding/bin//../util//seq-scripts/bin/seq-frag line 8.
Can't locate Fasta/Parser.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/amachado/SW/cs-scaffolding/bin//../util//seq-scripts/bin/seq-frag line 8.
BEGIN failed--compilation aborted at /home/amachado/SW/cs-scaffolding/bin//../util//seq-scripts/bin/seq-frag line 8."

In the basch i have the paths..

export PATH=/home/amachado/SW/cs-scaffolding:/home/amachado/SW/cs-scaffolding/util/bcftools:/home/amachado/SW/cs-scaffolding/util/htslib:/home/amachado/SW/cs-scaffolding/util/samtools:/home/amachado/SW/cs-scaffolding/util/seq-scripts/bin:/home/amachado/SW/cs-scaffolding/util/seqtk:/home/amachado/SW/cs-scaffolding/util/bcftools/misc:/home/amachado/SW/cs-scaffolding/lib

I should include other path's of cs-scaffolding?

Thank you again for all the support.
André

**Comment by AMMMachado** [comment]
Hi again dear thackl,
Apparently i solved the problem. 
I moved the /lib/Fastq and /lib/Fasta folders  to /usr/share/perl5 directory. 
The test, runned without problems and generate all the outputs. 
Thank you again for all the support.
André

**Comment by hughcross** [comment]
Hello, I am having the same problem. @INC contains the folder with those perl modules (full install done) and still says it is not loaded. I have added to perl5 directories (all listed in @INC), with no success. I also tried changing the use line in the seq-frag script to:
use lib '/path/to/lib/fasta/'; 

Nothing has worked so far. Anything else I can try? 
Thanks,

Hugh

**Comment by thackl** [comment]
Hm. I don't really have an idea. This sounds like it's a general perl issue, and how libraries are loaded on your system. I can't think of anything that would make this an issue with my libraries specifically. Can you run the following and send me the output?
```
find /path/to/where/you/installed/Fasta -name "*.pm"
perl -e 'print @INC; use Fasta::Parser'
```

**Comment by tshori** [comment]
The Bash Script is not exporting the env Variable $PERL5LIB 
If you export it manually, ut fixes it, like so: 
export PERL5LIB=/path/to/cross-species-scaffolding/lib/Fasta/lib:/path/to/cross-species-scaffolding/lib/Fastq/lib:$PERL5LIB 

You can also edit the shell script cross-mates to export that variable every time it run.
