### ISSUE TITLE
samtools mpileup

### ISSUE THREAD

**Issue by tshori** [thackl/cross-species-scaffolding#9]
Since samtools v2, mileup can multithread, is there are reason not to do so? I think it would greatly improve run time.

**Comment by thackl** [comment]
Hm, not sure what you mean with "v2". As far as I know, the latest version is samtools 1.10. And with that version, there is no multithread option for `samtools mpileup`. Only the note that `samtools mpileup` is deprecated and `bcftools mpileup` should be used in stead. Maybe that has also the multithreading? But if you find the right way to specify multithreading, through samtools or bcftools, let me know and I'd be happy to include it in the code

**Comment by tshori** [comment]
Sorry, I am using old nomenclature from before v1 was available. We used to call v0.2 version 2, that's when multithreading was implemented. In any case, in the current versions of samtools the flag -nthreads is applicate to all samtools, and it should work in mpileup.
